### ISSUE TITLE
Doesn't run (exe)

### ISSUE THREAD

**Issue by God-damnit-all** [Aeonss/WebtoonReader#5]
Just tried running it and it just outputs the following error:
```text
Traceback (most recent call last):
  File "WebtoonReader.py", line 385, in <module>
  File "WebtoonReader.py", line 47, in __init__
  File "CustomScroller.py", line 64, in __init__
  File "CustomScroller.py", line 206, in update_title_name
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
[13224] Failed to execute script 'WebtoonReader' due to unhandled exception!
```

**Comment by GustJc** [comment]
Thanks for reporting. 

I missed that. It only happens when you run the program for the first time, which is when the settings file is not yet created so I didn't catch that while testing.

I've made a fix #6. Now we just need to wait for it to be accepted.
